name: Deploy site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci --silent || npm install --silent
      - name: Build & prepare dist (deterministic banks)
        # Use the run_number so each workflow run produces reproducible banks for that run
        env:
          BANK_SEED: ${{ github.run_number }}
        run: npm run predeploy
      - name: Mirror dist into main/docs (for Pages configured to use main/docs)
        if: github.ref == 'refs/heads/main'
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # copy dist into a temp branch, update docs/ in main if there are changes
          git checkout --quiet main
          mkdir -p docs
          rsync -a --delete ./dist/ ./docs/ || (Get-ChildItem -Recurse -Force ./dist | ForEach-Object { Copy-Item -Path $_.FullName -Destination (Join-Path -Path ./docs -ChildPath ($_.FullName.Substring((Get-Item .).FullName.Length).TrimStart('\'))) -Force } ; exit 0)
          if [ -n "$(git status --porcelain docs)" ]; then
            git add docs
            git commit -m "ci: update docs/ with generated dist [skip ci]" || true
            git push origin main
          else
            echo "No changes to docs/"
          fi
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
