name: Validate dist artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install
        run: npm ci --silent || npm install --silent
      - name: Validate dist JSON
        run: npm run validate-dist
